name: sliver_fab
description: A wrapper widget allowing to place a widget on the edge of FlexibleSpacebar
version: 2.1.0
author: Marcin Szalek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/sliver_fab

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
